In [1]:
import numpy as np

In [23]:
#3.1
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list) * 4
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(arr[np.argmin(arr)])
print(arr[np.argmax(arr)])
print(np.min(arr))
print(np.max(arr))
print(arr[arr>20])

[ 80 108  36  48 124  68  16 200 156 140]
97.6
94.0
55.31582052180009
6
7
16
200
16
200
[ 80 108  36  48 124  68 200 156 140]


In [46]:
# 3.2
matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])
print(matrix.shape)
print(matrix[:,2])
print(matrix[1,:])
print(matrix * 2)
print(matrix.mean(axis = 0))
print(matrix.mean())
print(matrix.flatten())# it makes the matrix into a 1 by 1 matrix
print(np.argmax(matrix.flatten()))
print(np.argmin(matrix.flatten()))
print(np.unravel_index(np.argmax(matrix.flatten()),matrix.shape))
print(np.unravel_index(np.argmin(matrix.flatten()),matrix.shape))
print(matrix[matrix>15])
print(np.sort(matrix, axis = 1))

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[ 5 12 17  9  8 21 14  3  6 13 19 11]
5
7
(np.int64(1), np.int64(1))
(np.int64(1), np.int64(3))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [51]:
# 4
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def row_primes(a: np.ndarray) -> np.ndarray:
    primes = {2, 3, 5, 7, 11, 13, 17}
    keep_rows = []
    for row in a:
        for x in row:
            if x in primes:
                keep_rows.append(row)
                break 
    return np.array(keep_rows)
print(row_primes(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [62]:
# 5
arr = np.zeros((8,8))
print(arr)
    
def checkerboard():
    B = np.zeros((8, 8), dtype=int)
    B[::2, ::2] = 1
    B[1::2, 1::2] = 1
    return B
print(checkerboard())

def reverse_checkerboard():
    return 1 - checkerboard()
print(reverse_checkerboard())

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [65]:
# 6
def expansion(arr, n):
    return np.char.join(' ' * n, arr)
universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 2))

['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [68]:
# 7
def second_brightest(a: np.ndarray) -> np.ndarray:
    return np.sort(a, axis=1)[:, -2]
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)
print(second_brightest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
